#!/bin/bash

###USAGE: bash splitMatrix_rowTF [TE_result_matrix.txt]

#cd /home/Data/tenet_result_kyu/
#TE_mtrx=/home/Data/tenet_result_kyu/Bcell_merge_normal/TE_result_matrix.txt
#TE_mtrx=/home/Data/tenet_result_kyu/Bcell_merge_normal/TE_result_matrix_peaksInCol.txt

TE_mtrx="$1"
species="$2"

rm HumanTFs.txt
if [ "$species" == "human" ]
then 
	ln -s /home/Data_Drive_8TB_2/TENET_workshop/TENETPLUS/GO_symbol_human_regulation_of_transcription+sequence-specific_DNA_binding_list.txt HumanTFs.txt
  echo "human_!1"
elif [ "$species" == "mouse" ]
then
	ln -s /home/Data_Drive_8TB_2/TENET_workshop/TENETPLUS/GO_symbol_mouse_regulation_of_transcription+sequence-specific_DNA_binding_list.txt HumanTFs.txt
  echo "mouse_!1"
fi

cut -f 1 $TE_mtrx | sort > TE_Matrix.sort.tmp
sort HumanTFs.txt > HumanTFs.sort.tmp
comm -12 TE_Matrix.sort.tmp HumanTFs.sort.tmp > HumanTFs.comm.tmp
wc -l *tmp
cut -d$'\t' -f 1 $TE_mtrx > rowNames.tmp

for i in `cat  HumanTFs.comm.tmp`; do grep -n -w ^$i$ rowNames.tmp; done | cut -d":" -f 1 > LN.tmp
HumanTFs=`perl -pe 's/\n/$1,/' LN.tmp |sed 's/.$//'`
HumanHeadTFs=`echo "1,"$HumanTFs`

#https://stackoverflow.com/questions/40842008/subset-a-file-by-row-and-column-numbers
awk -v rows="$HumanHeadTFs" 'BEGIN{split(rows, a, ","); for (i in a) b[a[i]]} NR in b' $TE_mtrx > ${TE_mtrx%.txt}_rowTF.txt

rm *tmp

