#!/bin/bash

###USAGE: bash splitMatrix_rowTF [TE_result_matrix.txt]

#cd /home/Data/tenet_result_kyu/
#TE_mtrx=/home/Data/tenet_result_kyu/Bcell_merge_normal/TE_result_matrix.txt
#TE_mtrx=/home/Data/tenet_result_kyu/Bcell_merge_normal/TE_result_matrix_peaksInCol.txt

TE_mtrx="$1"
select_Peaks="$2"

#if [ ! -f "select_Peaks.txt" ]
#then ln -s /home/hg0426/TENET_merged_TF/GO_symbol_human_regulation_of_transcription+sequence-specific_DNA_binding_list.txt HumanTFs.txt
#$fi
#ln -s /home/Data/tenet_result_kyu/GO_symbol_human_regulation_of_transcription+sequence-specific_DNA_binding_list.txt HumanTFs.txt

cut -f 1 $TE_mtrx | sort > TE_Matrix.sort.tmp
sort $select_Peaks > select_Peaks.sort.tmp
comm -12 TE_Matrix.sort.tmp select_Peaks.sort.tmp > select_Peaks.comm.tmp
wc -l *tmp
cut -d$'\t' -f 1 $TE_mtrx > rowNames.tmp

for i in `cat  select_Peaks.comm.tmp`; do grep -n -w ^$i$ rowNames.tmp; done | cut -d":" -f 1 > LN.tmp
select_Peaks=`perl -pe 's/\n/$1,/' LN.tmp |sed 's/.$//'`
select_PeaksHeadTFs=`echo "1,"$select_Peaks`

#https://stackoverflow.com/questions/40842008/subset-a-file-by-row-and-column-numbers
awk -v rows="$select_PeaksHeadTFs" 'BEGIN{split(rows, a, ","); for (i in a) b[a[i]]} NR in b' $TE_mtrx > ${TE_mtrx%.txt}_select_Peaks.txt

rm *tmp

