#!/bin/bash

###USAGE: bash splitMatrix_colPK [TE_result_matrix.txt]

#cd /home/Data/tenet_result_kyu/
#TE_mtrx=/home/Data/tenet_result_kyu/Bcell_merge_normal/TE_result_matrix.txt

TE_mtrx="$1"

head -n 1 $TE_mtrx |sed 's/\t/\n/g' |grep -P "^[A-Za-z][^-:]*[-:][^-:]*[-:][^-:]*[0-9]$" |wc -l

PeakCols=`head -n 1 $TE_mtrx |sed 's/\t/\n/g' |grep -P "^[A-Za-z][^-:]*[-:][^-:]*[-:][^-:]*[0-9]$" |awk '{ printf "%s,", $0 }'|sed 's/.$//'`
TE='TE'
TePeakCols="$TE,$PeakCols" 	
echo $TePeakCols > TePeakCols.txt
#sed 's/,/\n/g' TePeakCols.txt |wc -l
#sed 's/,/\n/g' TePeakCols.txt |head -n 5
#sed 's/,/\n/g' TePeakCols.txt |tail -n 5

numPeaks=`head -n 1 $TE_mtrx |sed 's/\t/\n/g' | grep -P "^[A-Za-z][^-:]*[-:][^-:]*[-:][^-:]*[0-9]$" |wc -l`
divisor=2500
quotient=`expr $numPeaks / $divisor`

echo $numPeaks $divisor $quotient

#https://stackoverflow.com/questions/36471244/print-certains-columns-by-header-name-with-spaces-on-it-awk-sed
for ((i=0;i<=$quotient;i++))
do
echo $i
cut -d "," -f $((1+$divisor*$i))-$(($divisor*$((i+1)))) TePeakCols.txt > tmp$i
awk -v cols=`cat tmp$i` 'BEGIN{FS=OFS="\t"; nc=split(cols, a, ",")} NR==1{for (i=1; i<=NF; i++) hdr[$i]=i} {for (i=1; i<=nc; i++) if (a[i] in hdr) printf "%s%s", $hdr[a[i]], (i<nc?OFS:ORS)}' $TE_mtrx >TMP$i
done

paste TMP* > ${TE_mtrx%.txt}_colPK.txt
awk '{print NF; exit}' ${TE_mtrx%.txt}_colPK.txt

rm tmp* TMP* TePeakCols.txt

